"""add duration_minutes to quiz

Revision ID: 74794dff19bf
Revises: c01256548e14
Create Date: 2025-05-14 17:26:54.849316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74794dff19bf'
down_revision: Union[str, None] = 'c01256548e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.drop_column('quiz', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('quiz', 'duration_minutes')
    # ### end Alembic commands ###
