"""user tablosuna username ve full_name eklendi

Revision ID: 88d3dbff0c5d
Revises: eebd8b354e8b
Create Date: 2025-04-28 21:35:48.811848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d3dbff0c5d'
down_revision: Union[str, None] = 'eebd8b354e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
