"""add correct and wrong to score

Revision ID: 93fa1c5d2b9e
Revises: 88d3dbff0c5d
Create Date: 2025-05-04 14:46:51.929090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fa1c5d2b9e'
down_revision: Union[str, None] = '88d3dbff0c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('correct', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('wrong', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'wrong')
    op.drop_column('score', 'correct')
    # ### end Alembic commands ###
